"""Event schemas (pydantic) and ZeroMQ transport — the system's only runtime coupling.

Every running service publishes and subscribes through these versioned models;
bulk artifacts travel over the on-request query channel, never in events.
"""

from catsim.bus.codec import AnyEvent, decode_event, encode_event
from catsim.bus.events import (
    SCHEMA_VERSION,
    BlockConfigured,
    Command,
    CorrectionApplied,
    DecodeFinished,
    DecodeQueue,
    DecodeStarted,
    ErrorInjected,
    Event,
    InjectLoss,
    InjectPauli,
    IonLost,
    LogicalError,
    QubitReplaced,
    RoundStarted,
    RunFinished,
    SetDecoder,
    SetDecoderSlowdown,
    SetNoiseScale,
    SetPace,
    SetPaused,
    ShotFinished,
    SyndromeFired,
)
from catsim.bus.factory_events import (
    FactoryAccepted,
    FactoryAttempt,
    FactoryConfigured,
    FactoryRejected,
    LossDetected,
    ReplacementDispatched,
    ReplacementReady,
)
from catsim.bus.fleet_events import (
    ChipAdmitted,
    ChipAnnounce,
    ChipHeartbeat,
    ChipLeft,
    ChipLost,
    Drain,
    ScaleUp,
    SetChipMode,
    SetFocus,
    StopChip,
)
from catsim.bus.machine_events import (
    BlockAccounting,
    BlockAssignment,
    BlockHealth,
    ChipConfigured,
    ChipMode,
    ChipRole,
    ChipStatus,
    FactoryHealth,
    MachineStatus,
)
from catsim.bus.query import QueryError, QueryServer, query
from catsim.bus.transport import (
    DEFAULT_BACKEND_ADDRESS,
    DEFAULT_FRONTEND_ADDRESS,
    BusProxy,
    EventSink,
    EventSource,
    ZmqPublisher,
    ZmqSubscriber,
)

__all__ = [
    "DEFAULT_BACKEND_ADDRESS",
    "DEFAULT_FRONTEND_ADDRESS",
    "SCHEMA_VERSION",
    "AnyEvent",
    "BlockAccounting",
    "BlockAssignment",
    "BlockConfigured",
    "BlockHealth",
    "BusProxy",
    "ChipAdmitted",
    "ChipAnnounce",
    "ChipConfigured",
    "ChipHeartbeat",
    "ChipLeft",
    "ChipLost",
    "ChipMode",
    "ChipRole",
    "ChipStatus",
    "Command",
    "Drain",
    "CorrectionApplied",
    "DecodeFinished",
    "DecodeQueue",
    "DecodeStarted",
    "ErrorInjected",
    "Event",
    "EventSink",
    "EventSource",
    "FactoryAccepted",
    "FactoryAttempt",
    "FactoryConfigured",
    "FactoryHealth",
    "FactoryRejected",
    "InjectLoss",
    "InjectPauli",
    "IonLost",
    "LogicalError",
    "LossDetected",
    "MachineStatus",
    "QubitReplaced",
    "QueryError",
    "QueryServer",
    "ReplacementDispatched",
    "ReplacementReady",
    "RoundStarted",
    "RunFinished",
    "ScaleUp",
    "SetChipMode",
    "SetDecoder",
    "SetDecoderSlowdown",
    "SetFocus",
    "SetNoiseScale",
    "SetPace",
    "SetPaused",
    "ShotFinished",
    "StopChip",
    "SyndromeFired",
    "ZmqPublisher",
    "ZmqSubscriber",
    "decode_event",
    "encode_event",
    "query",
]
